global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "hono-api"
    static_configs:
      - targets: ["app:3000"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["host.docker.internal:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["host.docker.internal:8080"]
